checkout/urls.py
from django.urls import path
from .views import reserve_ticket, reservation_success, home, movie_list, movie_detail

app_name = 'checkout'

urlpatterns = [
    path('movie-detail/<int:movie_id>/', movie_detail, name='movie_detail'),
    path('movie_list/', movie_list, name='movie_list'),
    path('home/', home, name='home'),
    path('reserve-ticket/', reserve_ticket, name='reserve_ticket'),
    path('reservation-success/', reservation_success, name='reservation_success'),
]

cinema_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('api/', include('movie.urls')),
    path('', include('UserProfile.urls')),
    path('api/', include('event.urls')),
    path('', include('ticket.urls')),
    path('', include('checkout.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.urls import path
from .views import EventListCreateView

urlpatterns = [
    path('events/', EventListCreateView.as_view(), name='event-list-create'),
]

checkout/models.py
# models.py
from django.db import models
from admin_cinema.models import User
from movie.models import Movie
from django.utils import timezone
from cinema.models import Seat

class Reservation(models.Model):
    PAYMENT_METHOD_CHOICES = [
        ('cash', 'Cash'),
        ('credit_card', 'Credit Card'),
        ('paypal', 'PayPal'),
        # Thêm các lựa chọn thanh toán khác nếu cần
    ]

    # def calculate_total_price():
    #     return Seat.quantity * Seat.price

    # def get_user_email(self):
    #     return self.user.email

    # def get_movie_name(self):
    #     return self.movie.name

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    event_id = models.IntegerField(default=1)
    date = models.DateField(default=timezone.now)
    # total_price = calculate_total_price()
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, default='cash')

    def __str__(self):
        return f"{self.user.username} - {self.movie_id} - {self.event_id} - {self.date}"

checkout/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['user' ,'movie', 'date']

checkout/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Reservation
from admin_cinema.models import User
from movie.models import Movie
from .forms import ReservationForm

def is_admin(user):
    return user.is_authenticated and user.is_staff

@login_required(login_url="admin:login")
def reserve_ticket(request):
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user
            reservation.save()
            user = request.user
            user.points += 10  # Tăng điểm
            user.save()  # Lưu thay đổi
            return redirect('checkout:reservation_success')
    else:
        form = ReservationForm()

    movies = Movie.objects.all()
    return render(request, 'reserve_ticket.html', {'form': form, 'movies': movies})

# @login_required(login_url="admin:login")
# def reserve_ticket(request, movie_id):
#     if request.method == 'POST':
#         form = ReservationForm(request.POST)
#         if form.is_valid():
#             # Giả sử form này đã bao gồm tất cả trừ user và movie
#             reservation = form.save(commit=False)
#             reservation.user = request.user
#             # Tìm movie dựa trên movie_id và gán cho reservation
#             reservation.movie = Movie.objects.get(id=movie_id)
#             reservation.save()


#             user = request.user
#             user.points += 10  # Tăng điểm
#             user.save()  # Lưu thay đổi
#             return redirect('checkout:reservation_success')
#     else:
#         form = ReservationForm() 
    
#     movies = Movie.objects.all()
#     user_email = request.user.email  # Được sử dụng để hiển thị hoặc xử lý khác, không lưu trực tiếp vào model Reservation
#     selected_movie = Movie.objects.get(id=movie_id)
#     movie_name = selected_movie.name  # Tương tự như trên, dùng để hiển thị hoặc xử lý khác
    
#     # Chú ý: Phần tạo đối tượng Reservation dưới đây không cần thiết nếu bạn đã xử lý ở trên
#     # và có thể gây lỗi nếu bạn thực hiện nó ngoài block 'if POST' mà không kiểm tra dữ liệu đầu vào

#     context = {
#         'form': form,
#         'movies': movies,
#         'user_email': user_email,  # Đưa vào context để có thể sử dụng trong template
#         'movie_name': movie_name,  # Tương tự như trên
#     }

#     return render(request, 'reserve_ticket.html', context)

@login_required(login_url="admin:login")
def reservation_success(request):
    return render(request, 'reservation_success.html')

def home(request):
    return render(request, 'home.html')

def movie_list(request):
    movies = Movie.objects.all()
    return render(request, 'movie_list.html', {'movies': movies})

def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    actors = movie.actors.all()  # Lấy danh sách diễn viên của phim
    print(actors)
    return render(request, 'movie_detail.html', {'movie': movie, 'actors': actors})

checkout/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Document</title>
</head>

<body>
    <!-- navbar.html -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Trang Chủ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Chi Tiết</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-bell"></i> Thông Báo
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">
                        <i class="fas fa-cog"></i> Cài Đặt
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reserve_ticket' %}">
                        <i class="fas fa-ticket-alt"></i> Đặt Vé
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:login' %}">
                        <i class="fas fa-sign-in-alt"></i> Login
                    </a>
                </li>
                <!-- Thêm các nút khác nếu cần -->
            </ul>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

checkout/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Document</title>
</head>

<body>
    <!-- navbar.html -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'checkout:home' %}">Trang Chủ</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'checkout:movie_list' %}">
                        <i class="fas fa-list"></i> Danh sách phim
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fas fa-bell"></i> Thông Báo
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">
                        <i class="fas fa-cog"></i> Cài Đặt
                    </a>
                </li>
                <!-- Button trigger modal -->
                <!-- <li class="nav-item">
                    <a class="nav-link" action="{% url 'admin:logout' %}">
                        <i class="fas fa-sign-in-alt"></i> Logout
                    </a>
                </li> -->
                <form method="post" action="{% url 'admin:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="nav-link">
                        <i class="fas fa-sign-out-alt"></i> Logout
                    </button>
                </form>
                <!-- Thêm các nút khác nếu cần -->
            </ul>
        </div>
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

checkout/templates/movie_detail.html
{% extends 'home.html' %}

{% block content %}
<img src="{{ movie.image.url }}">
<h2>{{ movie.name }}</h2>
<p><strong>Ngày Ra Mắt:</strong> {{ movie.release_day }}</p>
<p><strong>Diễn Viên:</strong> {{ movie.actors.name }}</p>
<p><strong>Đạo Diễn:</strong> {{ movie.director }}</p>
<p><strong>Tóm Tắt Nội Dung:</strong> {{ movie.description }}</p>
<li class="nav-item">
    <a class="nav-link" href="{% url 'checkout:reserve_ticket' %}">
        <i class="fas fa-ticket-alt"></i> Đặt Vé
    </a>
</li>
{% endblock %}

checkout/templates/movie_list.html
{% extends 'home.html' %}
{% block content %}
<h2>Danh Sách Phim</h2>
<ul>
    {% for movie in movies %}
    <li>
        <img src="{{ movie.image.url }}">
        <p>{{ movie.name }}</p>
        <a class="nav-link" href="{% url 'checkout:movie_detail' movie.id %}">
            <i class="fas fa-info-circle"></i> Xem chi tiết
        </a>
        <a class="nav-link" href="{% url 'checkout:reserve_ticket' %}">
            <i class="fas fa-ticket-alt"></i> Đặt Vé
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

checkout/templates/reservation_success.html
{% extends 'home.html' %}

{% block content %}
  <h2>Đặt Vé Thành Công</h2>
  <p>Cảm ơn bạn đã đặt vé xem phim. Chi tiết vé sẽ được gửi vào email của bạn.</p>
{% endblock %}

checkout/templates/reserve_ticket.html
{% extends 'home.html' %}

{% block content %}
<h2>Đặt Vé</h2>

<form method="post" action="{% url 'checkout:reserve_ticket' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
      <a class="nav-link" href="{% url 'checkout:reserve_ticket' %}">
        <i class="fas fa-credit-card"></i> Thanh toán
      </a>
  </button>

  <!-- Modal -->
  <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Xác nhận đặt vé?</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-primary">Đồng ý</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Hủy</button>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}